version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: leaf
      POSTGRES_PASSWORD: leaf
      POSTGRES_DB: leaf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080